### ISSUE TITLE
"Wrong Password" dialog not showing up

### ISSUE THREAD

**Issue by danshaw** [pmbuko/KerbMinder#13]
Testing this out I am having an issue where there is no "wrong password" message displayed when a wrong password is input into the password box. It looks like I can put in the wrong password multiple times without any warning and to the user it looks like it was successful. This happens with both a bound to AD account and one that is not on the domain. Looking at the console logs it shows:

Ticket is not present
Initiating Ticket with password
Ticket initiation OK

It works fine when I type in the correct password. Testing this on a 10.11.5 Mac.

Hoping to find a solution as I would love to use this! Thanks.

**Comment by ftiff** [comment]
Fixed by v1.4.
@danshaw confirmed on Slack.
